import Head from "next/head";
import { styles } from "styled-system";
import data from './source.json';

export default function Home() {
    return (
      <div >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main >
          <h1 >
            title
          </h1>
          <p>
            description
          </p>
  
          <div>
            {data.map((result: any) => {
              const { id, rendered, date, image } = result;
              if (image) {
                return (                    
                  <div key={id} >
                    <h2><a href={'/'}>{rendered}</a></h2>
                    <h4>{date}</h4>
                    <div>
                      <a href = {'/'}>
                        <img src={image} alt="" width="40%" height="auto"></img> 
                      </a>
                    </div>
                    {/* <h3>{description}</h3> */}
                    {/* <p>{tag}</p> */}
                    <p>root domain</p>
                  </div>
                );
              } else {
                return (
                  <div key={id} >
                    <h2><a href={'/'}>{rendered}</a></h2>
                    <h4>{date}</h4>            
                    {/* <p>{tag}</p> */}
                    <p>root domain</p>
                  </div>
                );
              }
            })}
          </div>
        </main>
      </div>
    );
  };